module.exports = (function() {
var __MODS__ = {};
var __DEFINE__ = function(modId, func, req) { var m = { exports: {}, _tempexports: {} }; __MODS__[modId] = { status: 0, func: func, req: req, m: m }; };
var __REQUIRE__ = function(modId, source) { if(!__MODS__[modId]) return require(source); if(!__MODS__[modId].status) { var m = __MODS__[modId].m; m._exports = m._tempexports; var desp = Object.getOwnPropertyDescriptor(m, "exports"); if (desp && desp.configurable) Object.defineProperty(m, "exports", { set: function (val) { if(typeof val === "object" && val !== m._exports) { m._exports.__proto__ = val.__proto__; Object.keys(val).forEach(function (k) { m._exports[k] = val[k]; }); } m._tempexports = val }, get: function () { return m._tempexports; } }); __MODS__[modId].status = 1; __MODS__[modId].func(__MODS__[modId].req, m, m.exports); } return __MODS__[modId].m.exports; };
var __REQUIRE_WILDCARD__ = function(obj) { if(obj && obj.__esModule) { return obj; } else { var newObj = {}; if(obj != null) { for(var k in obj) { if (Object.prototype.hasOwnProperty.call(obj, k)) newObj[k] = obj[k]; } } newObj.default = obj; return newObj; } };
var __REQUIRE_DEFAULT__ = function(obj) { return obj && obj.__esModule ? obj.default : obj; };
__DEFINE__(1747316446043, function(require, module, exports) {
var t=require("@lspriv/wx-calendar/lib");const e=e=>e.map((e=>t.timestamp(e))).sort();class s{constructor(t){this.options=this.formOptions(t),this.disabled=[]}formOptions(t){return{style:{pointerEvents:"none",touchAction:"none",opacity:.3,...null==t?void 0:t.style}}}PLUGIN_INITIALIZE(t){this.service=t}PLUGIN_ON_ATTACH(t,e){e.pointer.show=!1,t.component._pointer_.show=!1}PLUGIN_ON_LOAD(t,e){e.checked=void 0}PLUGIN_ON_CHANGE(t,e,s){"click"!==e.source&&s.cancel(),t.component._pointer_.show=!1}PLUGIN_CATCH_TAP(t,e,s){const{wdx:a,ddx:r}=e.mark,i=t.component.data.panels[t.component.data.current].weeks[a].days[r];this.isDateDisabled(i)?s():t.component._pointer_.show=!0}PLUGIN_TRACK_DATE(t){return this.isDateDisabled(t)?{style:this.options.style}:null}PLUGIN_TRACK_YEAR(e){const s=new Map;for(let a=0;a<12;a++){const r=1===a&&t.isLeapYear(e.year)?t.GREGORIAN_MONTH_DAYS[a]+1:t.GREGORIAN_MONTH_DAYS[a];for(let i=0;i<r;i++){const r={year:e.year,month:a+1,day:i+1},n=t.getAnnualMarkKey({month:r.month,day:r.day});if(this.isDateDisabled(r)){const t=this.options.style.opacity;s.set(n,{style:{opacity:{light:t,dark:t}}})}}}return s.size?{marks:s}:null}PLUGIN_DATES_FILTER(t,e){return this.filter(e)}disable(t,e=!1){const s=[];e&&(s.push(...this.disabled),this.disabled=[]),this.disabled=this.mergeDisabled([...this.disabled,...t]);const a=s.length?this.mergeDisabled([...this.disabled,...s]):this.disabled;this.update(a)}filter(s){return s.flatMap((s=>{if(Array.isArray(s)){const a=[];let[r,i]=e(s);const n=i+864e5;for(let e=r;e<=n;e+=864e5){const s=t.normalDate(e);if(this.isDateDisabled(s)||e===n){if(e>r){const s=e-864e5,{year:i,month:n,day:o}=t.normalDate(r);if(s<=r)a.push({year:i,month:n,day:o});else{const{year:e,month:r,day:l}=t.normalDate(s);a.push([{year:i,month:n,day:o},{year:e,month:r,day:l}])}}r=e+864e5}}return a}return s&&this.isDateDisabled(s)?[]:s||[]}))}isDateDisabled(s){const a=t.timestamp(s);for(let r=this.disabled.length;r--;){const i=this.disabled[r];if(Array.isArray(i)){const t=e(i);if(a>=t[0]&&a<=t[1])return!0}else if(t.isSameDate(i,s))return!0}return!1}mergeDisabled(s){const a=[],r=s.flatMap((s=>Array.isArray(s)?s.length?s.length>1?[e(s)]:t.timestamp(s[0]):[]:t.timestamp(s))),i=r.filter((t=>Array.isArray(t)));for(let t=r.length;t--;){const e=r[t];if(Array.isArray(e)){const t=a.findIndex((t=>Array.isArray(t)&&!(e[0]>t[1]||e[1]<t[0])));if(t>=0){const s=a[t];a.splice(t,1,[Math.min(e[0],s[0]),Math.max(e[1],s[1])])}else a.push(e)}else{let t=i.find((t=>e>=t[0]&&e<=t[1]));t||(t=a.find((t=>!Array.isArray(t)&&t===e))),t||a.push(e)}}return a.map((e=>Array.isArray(e)?e.map((e=>t.normalDate(e))):t.normalDate(e)))}update(t){this.service.updateRange(t.map((t=>Array.isArray(t)?t:[t])));const e=[...new Set(t.flatMap((t=>{if(Array.isArray(t)){const e=[];for(let s=t[0].year;s<=t[1].year;s++)e.push(s);return e}return t.year})))];this.service.updateAnnuals(e)}}s.KEY="wc-plugin-disabled";const a=s.KEY;exports.DISABLED_PLUGIN_KEY=a,exports.DisabledPlugin=s;

}, function(modId) {var map = {}; return __REQUIRE__(map[modId], modId); })
return __REQUIRE__(1747316446043);
})()
//miniprogram-npm-outsideDeps=["@lspriv/wx-calendar/lib"]
//# sourceMappingURL=index.js.map